### PR TITLE
Rbss

### PR DESCRIPTION
**Pull request by byanko55**
Commit Summary:

**New feature**
* Giscus: [open API-based comments system](https://giscus.app/)
* Represent hit/comment counts

**Minor Update**
* Adjust home title/avatar position
* Remove the background color of page description in mobile/tablet view

### CODE REVIEW

**Review by mgarrixx — COMMENTED** [review]
image

Nah.. It's not good

**Comment by mgarrixx** [comment]
image


wo, WHAT HAVE YOU DONE? /ᐠ_ ꞈ _ᐟ\

**Comment by byanko55** [comment]
That's terrifying. Check the [new one](https://github.com/byanko55/jekyll-theme-MacOS/pull/21/commits/e1e79cfbe1d4d388bc2dcf6ff1b8d7a4c850014e).

**Review by mgarrixx — COMMENTED** [review]
I can't see the comments count, and got an error on console whenever I refreshed the page:


> GET https://giscus.app/api/discussions?repo=mgarrixx%40mgarrixx.github.io&term=markdown%2520guide&category=Q%26A&number=0&strict=false&first=15 404 (Not Found)

**Review by cvlian — COMMENTED** [review]
And one more thing, You have to update the `#num-comments` via event listener. It also takes time to load the `.gsc-comment` elements, so locating those codes to the bottom of lines won't work at all.

You may want follow these:
* https://github.com/orgs/giscus/discussions/113#discussioncomment-991044
* https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#giscus-to-parent-message-events

**Review by cvlian — APPROVED** [review]
Shall we wrap up this part for now?

**Review by mgarrixx — APPROVED** [review]
yah, Indeed.

**Pull request merged**
