### PR TITLE
Hot Fix: git page build error

### PR DESCRIPTION
**Pull request by byanko55**
**New feature**
* page hit counter

**Minor Update**
* resolve the git page build error

### CODE REVIEW

**Review by cvlian — CHANGES_REQUESTED** [review]
Adding `#` doesn't resolve the build issue. Remove the symbol `-` from in global param definition; some symbol may violoate the syntax of `calc`. 

(My suggestion is, to replace the suffix `-wd` to `width`)

**Review by cvlian — APPROVED** [review]
Yeah, That's it

**Review by mgarrixx — APPROVED** [review]
I'd watched it works with @cvlian.

**Comment by byanko55** [comment]
@mgarrixx, let me close the issue #22 then.

**Comment by mgarrixx** [comment]
> @mgarrixx, let me close the issue #22 then.

Sure

**Pull request merged**
