### PR TITLE
Fix Bugs & Change dark mode theme

### PR DESCRIPTION
**Pull request by byanko55**
Commit Summary:

**New feature**
* Show pagination tree in post

**Minor Update**
* Set default header font-family/color
* Move copyright to left sidebar
* Fix: nav not opened according to current path tree
* Fix: blank area between sidebar and inner-content in mobile view
* Fix: page description overflow
* Change dark mode color palette

### CODE REVIEW

**Comment by byanko55** [comment]
The main reasons that I had modified Dark mode theme:
* Glitter effects on post border makes one's eyes tired
* Too colorful palette
* To make contrast to the text contents, it'd be better to darken the background

Review this PR with those in mind

**Comment by cvlian** [comment]
Could you choose a little bit more dim font-tone for the default? (as well as headers: h1, h2, ...)

Aside that, don't forget to join @mgarrixx in collaborator

**Review by cvlian — COMMENTED** [review]
Could you choose a little bit more dim font-tone for the default? (as well as headers: h1, h2, ...)

**Comment by cvlian** [comment]
Aside that, don't forget to join @mgarrixx in collaborator

**Comment by byanko55** [comment]
> Aside that, don't forget to join @mgarrixx in collaborator

Aleardy done, he is just not showed as no commits had been published from him.

**Review by mgarrixx — COMMENTED** [review]
Check this out, the category name is placed too close to the top.

image

**Comment by byanko55** [comment]
I fixed the requests from both of you(@cvlian, @mgarrixx).

Fun thing is I'd misused the `yellowgreen`, it's slightly diffrent with `greenyellow`. Don't be confused!
The cancled(re-pushed) commit(`66a9708`) is for that.

**Comment by mgarrixx** [comment]
> I fixed the requests from both of you(@cvlian, @mgarrixx).
> 
> Fun thing is I'd misused the `yellowgreen`, it's slightly diffrent with `greenyellow`. Don't be confused! The cancled(re-pushed) commit(`66a9708`) is for that.

Something new for me too.

**Review by mgarrixx — APPROVED** [review]
I checked all of the feedbacks were properly applied to the previous commits. Ask to @cvlian   to conform it.

**Review by cvlian — APPROVED** [review]
Anyways, you managed them well.

**Pull request merged**
