### PR TITLE
Improve page performance

### PR DESCRIPTION
**Pull request by byanko55**
**New Features**
* Lazy image loading
* Load custom fonts locally (not from CDN)
* Disable star background in mobile/tablet view

**Minor Updates**
* Utilize lightweight resources

**Bug Fixes**
* The 6th (last) favicon of contact box is trimmed
* post info area is out of inner-content

### CODE REVIEW

**Review by mgarrixx — COMMENTED** [review]
image

`code` and `table` elements have same background color.

**Comment by byanko55** [comment]
Update details:
* paint dark color to <body>
* change color of code snippet
* remove text shadow of the post title in mobile view

**Review by mgarrixx — APPROVED** [review]
OK that's enough

**Review by cvlian — APPROVED** [review]
Nothing to point out yet.

**Pull request merged**
