### PR TITLE
Update stylesheet & Fix issues related with external APIs

### PR DESCRIPTION
**Pull request by byanko55**
**New Features**
* Giscus user guide
* Expose post entity ahead of the category items in search result

**Minor Updates**
* Remove magnifying glass icon next to the search input area
* Update stylesheet

**Bug Fixes**
* Resolve indentation issues in search & categorization
* Posting date is not displayed
* Search result include Home URL
* Top arrow button is not displayed
* Wrong format for Goatcounter user code

### CODE REVIEW

**Review by mgarrixx — COMMENTED** [review]
Please don't forget to erase redundant comments in `.scss` files

**Comment by cvlian** [comment]
> I'd not seen any other functional issues. Thanks to @cvlian, minor bugs had been corrected in time and I inspected the demo website whenever a new build happens. It is working nicely now.

I had checked too @byanko55.

Think this is just an alpha test. You would not have to do patches all at once.

**Comment by cvlian** [comment]
Looks like the text inside a code element is floating high

image

**Comment by cvlian** [comment]
Think this is just an alpha test. You would not have to do patches all at once.

**Comment by byanko55** [comment]
> Looks like the text inside a code element is floating high

Which OS/device type did you test on?

**Comment by cvlian** [comment]
> > Looks like the text inside a code element is floating high
> 
> Which OS/device type did you test on?

Firefox (CentOS 9 stream)

**Comment by byanko55** [comment]
So, how about this? It seems the floating text is due to the inherent characteristic of 'Consolas' font. I selected new font-family to resolve it. 

image

**Comment by cvlian** [comment]
> So, how about this? It seems the floating text is due to the inherent characteristic of 'Consolas' font. I selected new font-family to resolve it.

Looks better than it was. Thanks.

**Review by cvlian — APPROVED** [review]

**Review by mgarrixx — APPROVED** [review]

**Pull request merged**
